name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - uses: actions/cache@v4
      with:
        path: ~/voxelwise_tutorials_data/shortclips
        key: shortclips-dataset

    - name: Install dependencies
      run: |
        pip install -U setuptools
        pip install -U wheel
        # install himalaya from source to get early testing
        pip install git+https://github.com/gallantlab/himalaya.git
        pip install -e ."[github]"
        # use neurodebian installer for travis
        bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
        sudo apt-get update -qq
        sudo apt-get install git-annex-standalone

    - name: Lint with flake8
      run: |
        pip install -q flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --ignore=E402,C901 --max-line-length=127 --statistics

    - name: Config git-annex
      run: |
        # add some git config for git-annex
        git config --global user.email "github-actions@example.com"
        git config --global user.name "Github Actions"

    - name: Test with pytest
      run: |
        # run the tests
        pip install -q pytest pytest-cov codecov
        pytest --cov=./

    - name: Run codecov
      run: |
        codecov

    - name: Run some tutorials
      run: |
        # run tutorials with a shortcut option to skip model fitting
        HIMALAYA_SKIP_FIT=True python tutorials/shortclips/00_download_shortclips.py
        HIMALAYA_SKIP_FIT=True python tutorials/shortclips/01_plot_explainable_variance.py
        HIMALAYA_SKIP_FIT=True python tutorials/shortclips/02_plot_ridge_regression.py
        HIMALAYA_SKIP_FIT=True python tutorials/shortclips/03_plot_wordnet_model.py
        HIMALAYA_SKIP_FIT=True python tutorials/shortclips/04_plot_hemodynamic_response.py
        HIMALAYA_SKIP_FIT=True python tutorials/shortclips/05_plot_motion_energy_model.py
        HIMALAYA_SKIP_FIT=True python tutorials/shortclips/06_plot_banded_ridge_model.py
